### PR TITLE
Implement onChangeStart callback to AreaHighlight

### PR DESCRIPTION
**Pull request by Fensterbank**
In our project we have the use case, that we toggle between area and text selection with a button instead of pressing the alt key.
This resulted in the behavior that while in area mode, moving or resizing an existing area would result in the start of a new area selection the same time.
grafik

To prevent this, I added a callback `onChangeStart` to `AreaHighlight`, so my control is able to remove the `enableAreaSelection` callback as soon as a drag or resizing of an existing area is started.

Since the `shouldStart` check using `enableAreaSelection()` will be triggered before `onChangeStart`, I do not have the information of a started drag already inside of `enableAreaSelection()`, so I have to remove that callback after the `MouseSelection` component is already doing its job.

Since this will result in the unmounting of the `MouseSelection` component, I had to refactor things in this component to properly remove all event listeners in `componentWillUnmount()` to avoid state updates of an unmounted component.

Sample Code:
```jsx
      <AreaHighlight
        highlight={highlight}
        onChangeStart={() => setAreaChanging(true)}
        onChange={(boundingRect) => {
          setAreaChanging(false);
          updateHighlight(
            highlight.id,
            { boundingRect: viewportToScaled(boundingRect) },
            { image: screenshot(boundingRect) },
          );
        }}
      />
```
```jsx
      <PdfHighlighter
        pdfDocument={doc}
        enableAreaSelection={
          mode === 'areaSelection' && !areaChanging ? () => true : null
        }
        …
      </PdfHighlighter>
```

### CODE REVIEW

**Comment by agentcooper** [comment]
@Fensterbank Thank you! Looks good. Could you please fix the current merge conflicts, and then I'll merge it.

**Comment by Fensterbank** [comment]
@agentcooper Thanks. While I fixed the conflicts, I now get errors on starting an area selection.
I'm not sure, if this has something to do with the merge or if I did a mistake somewhere, i think the ladder.

I want to fix this, but I've a lot to do at the moment, so let's put this PR on hold until I could take a deeper look.

**Comment by filipbasara0** [comment]
@Fensterbank Hi, I am working on a project where I need to implement a similar feature. Specifically I have to toggle between AreaHiglight and  TextHighlight modes. While working on that feature, I noticed you PR, where you are doing pretty much the same thing. That said, I was wondering if you had the time to figure out what issues caused the error?

Thank you in advance!

**Comment by Fensterbank** [comment]
Hi @filipbasara0 

> Specifically I have to toggle between AreaHiglight and TextHighlight modes.

Yep, that's exactly the case.

Unfortunately I could not take a deeper look. I had some issues on resizing and it must have something to do with my changes (all tough I cannot reproduce it in my project, where we use this PR).

What's your time frame on your feature? I think I should be able to take another look and finish this PR this week.

**Comment by filipbasara0** [comment]
Hi,

Thank you for a quick response!

Oh, I understand. 

Well, I have several things left to do before starting with the toggle feature. That will probably take me this week and maybe even some days in the following week. 

So, take your time, no rush. 

Thank you so much for your help!

**Pull request closed without merging**
