### PR TITLE
Update pdfjs

### PR DESCRIPTION
**Pull request by sudarshanshenoy**
Hi Artem, 

I would like to contribute to this project. I was using this library with react boilerplate and was facing issue because of pdfjs used was not compatible with webpack 4. I have updated it.

I am new to open source contribution. Guide me if If there is any thing I have missed.

### CODE REVIEW

**Comment by sudodoki** [comment]
For my needs it works with webpack 4 (4.39.1) and pdfjs-dist (2.0.489) just fine

**Comment by dev1digichorus** [comment]
This is very helpful. I was struggling from last 4 days to solve this issue

**Comment by khushisheth2324** [comment]
We are also facing the same issue. Please merge this. Thanks.

**Comment by sudarshanshenoy** [comment]
I closed the pull request by mistake. I have reopened it. I am glad it helped.

**Comment by Allan690** [comment]
Anyone encountered this issue where the document does not load?

**Comment by sudodoki** [comment]
@Allan690 if it's issue with pdfjs, you'll see an error message in console, I think. There's an issue in PdfLoader where it doesn't quite work when the url is not set right away, and updates at some point

**Comment by agentcooper** [comment]
I've published [3.0.0](https://www.npmjs.com/package/react-pdf-highlighter/v/3.0.0) with PDF.js updated to 2.2.228.

**Pull request closed without merging**
