### PR TITLE
General reusability fixes

### PR DESCRIPTION
**Pull request by jsg2021**
@agentcooper Once I was able to get the document updating, I ran into some small quirks that this should address.

- Cleanup resources on document changes and unmount. 
- Better event listening.
- Update dependencies.

### CODE REVIEW

**Comment by agentcooper** [comment]
This looks great! I remember last time I've tried to update Flow, I've ran into some typings issues. They seem to show up now in CI. Do you think you'll be able to fix those?

**Comment by jsg2021** [comment]
@agentcooper sure! I take a stab at it. I only updated flow because the pinned version didn't work in vs code.

**Comment by jsg2021** [comment]
In exploring to fix types & tests I reproduced #74 ... this is caused by importing `pdfjs-dist` ... I fixed it by importing `pdfjs-dist/lib/pdf` instead. The `main` in it's package.json points to a UMD bundle produced by their build.

**Comment by jsg2021** [comment]
The check failed because it's trying to publish the gh-pages... not sure that should happen on PRs.

**Comment by jsg2021** [comment]
Fixes #74 by importing lib over umd.
Fixes #75 and #77 -- makes irrelevant.

**Comment by agentcooper** [comment]
I think there is a small issue, when trying clicking "Toggle PDF document" button (in the sidebar, under the highlights), the document isn't switching (spinner hangs forever). Can you please look into it? It works on https://agentcooper.github.io/react-pdf-highlighter/.

**Comment by jsg2021** [comment]
Ah, the worker cleanup is async and when using a shared worker the discarded document cleanup was stomping on the new document. I chained them so they have to finish in order.

**Comment by jsg2021** [comment]
The component will now respond to resizes :)

**Comment by jsg2021** [comment]
The last commit fixes #33

**Comment by jsg2021** [comment]
@agentcooper I think this is ready. :)

**Comment by jsg2021** [comment]
@agentcooper I hope all is well. Is there anything I can do to help move this along? Thoughts/reservations on the changes?

**Comment by shaynethiessen** [comment]
Can we get this merged in?

**Comment by jsg2021** [comment]
I've been sitting on b4df9f5 for a while now. It's been using a locally patched version of pdfjs-dist, now that mozilla published my fix there, I'm including support for it here.

**Comment by agentcooper** [comment]
Great work! Published in 3.3.0.

**Comment by c3founder** [comment]
Hey, Jonathan @jsg2021 is it possible for you to give an option for disabling the ResizeObserver? I have the pdf in an iframe and added a manual zoom. But the ResizeObserver takes over when the manual zoom exceeds the iframe-width and resizes the pdf back to fit the iframe width. 

The simplest solution that I can think of is an option to disable the automatic resize in the highlighter. 

Thanks!

**Comment by jsg2021** [comment]
@c3founder I'm not working on a project that uses this at the moment, but you can make PR. :) The code-spaces feature allows you to spin up a working env in the browser.

**Comment by jsg2021** [comment]
I just did a quick skim... you could add a ref callback to the PdfHighlighter: `ref={x => x?.resizeObserver.disconnect()}`

**Comment by c3founder** [comment]
Awesome. Thanks for the hint.

**Comment by BaniGrisson** [comment]
I've been trying to make `ref={x => x?.resizeObserver.disconnect()}` work for a while now with no results.

If I set the default zoom to be bigger than the screen, it does zoom in.
Then, if I try to zoom in, it doesn't.
Then, if I try to zoom out, it does.
Then, I try to zoom back in, it doesn't.

In all cases the `window.PdfViewer.viewer.currentScaleValue` variable doesn't go over the "allowed" amount. Even if I'm seeing a huge pdf, because of the default zoom, the variable starts at 2 and goes down from there (though the actual zoom goes down from, for example, six).

Any insight? I'm so confused. Thanks in advanced!

**Comment by codepeach** [comment]
@BaniGrisson Do you by any chance remember how you solved this?

**Comment by igoroalonge** [comment]
> @BaniGrisson Do you by any chance remember how you solved this?

I've been using this:
```js
onClick={() => {
  ref.current?.resizeObserver?.disconnect()
  ref.current?.viewer.decreaseScale()
}}
```

**Comment by BaniGrisson** [comment]
> > @BaniGrisson Do you by any chance remember how you solved this?
> 
> I've been using this:
> ```js
> onClick={() => {
>   ref.current?.resizeObserver?.disconnect()
>   ref.current?.viewer.decreaseScale()
> }}
> ```

Hi friend. I didn't. Fresh install of everything and a new project was the only fix (and only after several months). Cheers!

**Pull request merged**
