### PR TITLE
Handle changes to the pdf document

### LINKED ISSUE #60: Component  PdfLoader does not refresh when pdfFileUrl  changes
I managed to set up an application based on the example of this repo with electron.js, I added a button to load new pdf files.  The highlight sidebar updates every time when I load a new pdf file and its associated annotations, but <PdfLoader> component does not refresh.

I tried to create a simple component such as

```js
const DemoComp = (props) => (
        <h2>{props.pdfFileUrl}</h2>
);
...       
{pdfFileUrl ? (
          <DemoComp pdfFileUrl={pdfFileUrl} />
) : null
```

the DemoComp updated as expected so the React state and its refresh cycle are working properly.

@agentcooper May you please give me some hints to resolve the issue?

thanks

### PR DESCRIPTION
**Pull request by jsg2021**
Fixes #60 
This reuses the same load logic from the mount.
Suplants #64

### CODE REVIEW

**Comment by jsg2021** [comment]
@agentcooper are you still maintaining this? I'd like to contribute my fixes/updates back if you'll have them.

**Comment by agentcooper** [comment]
Hey @jsg2021, I will really try to check and merge this today!

**Comment by jsg2021** [comment]
Awesome thanks!

**Comment by jsg2021** [comment]
@agentcooper let me know if I can help in any way

**Comment by agentcooper** [comment]
@jsg2021 Thanks for the contribution! I've published it in 3.2.0.

**Pull request merged**
